### ISSUE TITLE
В TipController.update(..) вызывается не верный метод серивса

### ISSUE THREAD

**Issue by sergey-oreshkin** [sergey-oreshkin/tipster-server#12]
`@PutMapping
    public TipDto update(@Valid @RequestBody TipDto tipDto) throws NotFoundException {
        log.info("Updates tips with id {}", tipDto.getId());
        Tip tip = tipMapper.toTips(tipDto);
        return tipMapper.toDto(tipService.create(tip));
    }`
должен вызываться tipService.update(..)

**Comment by aBoyarov** [comment]
И здесь исправил
